topology:
  switches:
    s1:
      role: core
      dpid: null
    s2:
      role: aggregation
      dpid: null
    s3:
      role: aggregation
      dpid: null
    ap1:
      role: access
      dpid: null
    ap2:
      role: access
      dpid: null
    ap3:
      role: access
      dpid: null
    ap4:
      role: access
      dpid: null
    ap5:
      role: access
      dpid: null

  aggregation_map:
    s2:
      - ap1
      - ap2
      - ap3
    s3:
      - ap4
      - ap5

  aggregation_ports:
    s2:
      core_port: 1
      ap_ports:
        ap1: 2
        ap2: 3
        ap3: 4
    s3:
      core_port: 1
      ap_ports:
        ap4: 2
        ap5: 3
  core_ports:
    s1:
      s2: 1
      s3: 2
  ap_slice_map:
    ap1: vle
    ap2: student_portal
    ap3: admin
    ap4: iot
    ap5: general

  links:
    core_to_aggregation:
      - [s1, s2]
      - [s1, s3]
    aggregation_to_access:
      - [s2, ap1]
      - [s2, ap2]
      - [s2, ap3]
      - [s3, ap4]
      - [s3, ap5]

  link_capacity_bps: 100_000_000

controller:
  host: 127.0.0.1
  port: 6633
  stats_interval_sec: 2
  barrier_timeout_sec: 5.0
  barrier_warn_interval_sec: 30.0
  meter_settle_sec: 0.5

upf:
  eth0_mac: "02:00:00:00:00:ff"
  gw_mac: "02:00:00:00:0c:00"
  gw_ip: "10.100.200.200"
  s1_upf_port_name: "s1-upf"
