/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSlicesRouteImport } from './routes/_app/slices'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppSlicesVleRouteImport } from './routes/_app/slices/vle'
import { Route as AppSlicesStudentPortalRouteImport } from './routes/_app/slices/student-portal'
import { Route as AppSlicesIotRouteImport } from './routes/_app/slices/iot'
import { Route as AppSlicesGeneralRouteImport } from './routes/_app/slices/general'
import { Route as AppSlicesAdminRouteImport } from './routes/_app/slices/admin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSlicesRoute = AppSlicesRouteImport.update({
  id: '/slices',
  path: '/slices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSlicesVleRoute = AppSlicesVleRouteImport.update({
  id: '/vle',
  path: '/vle',
  getParentRoute: () => AppSlicesRoute,
} as any)
const AppSlicesStudentPortalRoute = AppSlicesStudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => AppSlicesRoute,
} as any)
const AppSlicesIotRoute = AppSlicesIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AppSlicesRoute,
} as any)
const AppSlicesGeneralRoute = AppSlicesGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSlicesRoute,
} as any)
const AppSlicesAdminRoute = AppSlicesAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppSlicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agent': typeof AppAgentRoute
  '/settings': typeof AppSettingsRoute
  '/slices': typeof AppSlicesRouteWithChildren
  '/slices/admin': typeof AppSlicesAdminRoute
  '/slices/general': typeof AppSlicesGeneralRoute
  '/slices/iot': typeof AppSlicesIotRoute
  '/slices/student-portal': typeof AppSlicesStudentPortalRoute
  '/slices/vle': typeof AppSlicesVleRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AppAgentRoute
  '/settings': typeof AppSettingsRoute
  '/slices': typeof AppSlicesRouteWithChildren
  '/': typeof AppIndexRoute
  '/slices/admin': typeof AppSlicesAdminRoute
  '/slices/general': typeof AppSlicesGeneralRoute
  '/slices/iot': typeof AppSlicesIotRoute
  '/slices/student-portal': typeof AppSlicesStudentPortalRoute
  '/slices/vle': typeof AppSlicesVleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agent': typeof AppAgentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/slices': typeof AppSlicesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/slices/admin': typeof AppSlicesAdminRoute
  '/_app/slices/general': typeof AppSlicesGeneralRoute
  '/_app/slices/iot': typeof AppSlicesIotRoute
  '/_app/slices/student-portal': typeof AppSlicesStudentPortalRoute
  '/_app/slices/vle': typeof AppSlicesVleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/settings'
    | '/slices'
    | '/slices/admin'
    | '/slices/general'
    | '/slices/iot'
    | '/slices/student-portal'
    | '/slices/vle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/settings'
    | '/slices'
    | '/'
    | '/slices/admin'
    | '/slices/general'
    | '/slices/iot'
    | '/slices/student-portal'
    | '/slices/vle'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agent'
    | '/_app/settings'
    | '/_app/slices'
    | '/_app/'
    | '/_app/slices/admin'
    | '/_app/slices/general'
    | '/_app/slices/iot'
    | '/_app/slices/student-portal'
    | '/_app/slices/vle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slices': {
      id: '/_app/slices'
      path: '/slices'
      fullPath: '/slices'
      preLoaderRoute: typeof AppSlicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slices/vle': {
      id: '/_app/slices/vle'
      path: '/vle'
      fullPath: '/slices/vle'
      preLoaderRoute: typeof AppSlicesVleRouteImport
      parentRoute: typeof AppSlicesRoute
    }
    '/_app/slices/student-portal': {
      id: '/_app/slices/student-portal'
      path: '/student-portal'
      fullPath: '/slices/student-portal'
      preLoaderRoute: typeof AppSlicesStudentPortalRouteImport
      parentRoute: typeof AppSlicesRoute
    }
    '/_app/slices/iot': {
      id: '/_app/slices/iot'
      path: '/iot'
      fullPath: '/slices/iot'
      preLoaderRoute: typeof AppSlicesIotRouteImport
      parentRoute: typeof AppSlicesRoute
    }
    '/_app/slices/general': {
      id: '/_app/slices/general'
      path: '/general'
      fullPath: '/slices/general'
      preLoaderRoute: typeof AppSlicesGeneralRouteImport
      parentRoute: typeof AppSlicesRoute
    }
    '/_app/slices/admin': {
      id: '/_app/slices/admin'
      path: '/admin'
      fullPath: '/slices/admin'
      preLoaderRoute: typeof AppSlicesAdminRouteImport
      parentRoute: typeof AppSlicesRoute
    }
  }
}

interface AppSlicesRouteChildren {
  AppSlicesAdminRoute: typeof AppSlicesAdminRoute
  AppSlicesGeneralRoute: typeof AppSlicesGeneralRoute
  AppSlicesIotRoute: typeof AppSlicesIotRoute
  AppSlicesStudentPortalRoute: typeof AppSlicesStudentPortalRoute
  AppSlicesVleRoute: typeof AppSlicesVleRoute
}

const AppSlicesRouteChildren: AppSlicesRouteChildren = {
  AppSlicesAdminRoute: AppSlicesAdminRoute,
  AppSlicesGeneralRoute: AppSlicesGeneralRoute,
  AppSlicesIotRoute: AppSlicesIotRoute,
  AppSlicesStudentPortalRoute: AppSlicesStudentPortalRoute,
  AppSlicesVleRoute: AppSlicesVleRoute,
}

const AppSlicesRouteWithChildren = AppSlicesRoute._addFileChildren(
  AppSlicesRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSlicesRoute: typeof AppSlicesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSlicesRoute: AppSlicesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
