mcc: "208"
mnc: "93"
nci: "0x000000010"
idLength: 32
tac: 1
linkIp: 127.0.0.1
ngapIp: gnb.free5gc.org
gtpIp: gnb.free5gc.org
amfConfigs:
  - address: amf.free5gc.org
    port: 38412
slices:
  - sst: 0x1
    sd: 0x000001
  - sst: 0x1
    sd: 0x000002
  - sst: 0x1
    sd: 0x000003
  - sst: 0x2
    sd: 0x000004
  - sst: 0x1
    sd: 0x000005
ignoreStreamIds: true
